#!/bin/bash
#Git Commit Program
#Author : Jim Gogarty
#Version : 0.9
#website : NONE AS YET
#Report Bugs to github.
#
#
#This program will run the git commit comands for the user
#user will have to enter username and password at final stage
#
#if you would like to have this program as a ready to run program
#enter the following command
#
#export PATH=$PATH:/path/to/dir
#where "/path/to/dir is where you have located this script
#

#VARIABLES
SCRIPTS="/home/jim/scripts"
SCRIPTS_CHILD="/home/jim/scripts/*"
MESSAGE="$@"
LOOP=1
ME=1
#FUNCTIONS

#git commit and push commands
function gitpush ()
{
	echo "Commiting changes to github"
	git add .
	git commit -m "$MESSAGE"
	git push -u origin master
}

#check dir 
function check ()
{
	#if working dir is in scripts or in its childern commit changes
	#if not cd to "scripts folder and continue
	while [ $LOOP -eq 1 ]; do 
		if [[ $PWD = $SCRIPTS ]] || [[ $PWD = $SCRIPTS_CHILD ]]  ; then
			
			LOOP=0
				
			gitpush 
		else
			echo "You are not in the Scripts directorys."
			echo "Would you like to chnge to the folder and commit changes."
			read -p  "Enter \"y\" for yes or \"n\" for no." answer
			if [ $anser = "y" ] ; then 
				LOOP=0
				cd ~/scripts
				gitpush
			elif [ answer = "n" ]; then 
				echo "Ok. We will now exit the program."
				LOOP=0
			else
				echo "You have not entered a correct option."
				echo "Please re-enter your choice."
				read answer2
				answer = $answer2	
			fi #anser
		fi #dir 
	done #while loop
}

#MAIN
clear
#if no arguments 
while [ $ME -eq 1 ]; do
	#-z will check if the variable $MESSAGE is a null value
	if [ -z $MESSAGE ]; then
		 
		echo "You have not entered a commit message."
		echo "Would you like to enter one now ?"
		read -p  "Enter \"y\" for yes or \"n\" for no.  " option
		if [ $option = "y" ]; then
			read -p  "Please enter your commit message. " commitMessage
			
			echo "Your git commit message is : $commitMessage"
			MESSAGE="$commitMessage"
			ME=0
			check
		elif [ $option = "n" ]; then
			echo "The program will now close."
			ME=0
		elif [ $option -eq "" ]; then
			
			echo "You have not entered a correct option."
                        echo "Please enter your option again."

		else 
			echo "You have not entered a correct option."
			echo "Please enter your option again."
			

		fi
	else	
		
		ME=0
		check
	fi	
done
